export enum LocationCode {
    East_Asia = 'eastasia',
    Southeast_Asia = 'southeastasia',
    Central_US = 'centralus',
    East_US = 'eastus',
    East_US_2 = 'eastus2',
    West_US = 'westus',
    North_Central_US = 'northcentralus',
    South_Central_US = 'southcentralus',
    North_Europe = 'northeurope',
    West_Europe = 'westeurope',
    Japan_West = 'japanwest',
    Japan_East = 'japaneast',
    Brazil_South = 'brazilsouth',
    Australia_East = 'australiaeast',
    Australia_Southeast = 'australiasoutheast',
    South_India = 'southindia',
    Central_India = 'centralindia',
    West_India = 'westindia'
}